services:
  postgres:
    image: 'postgres:latest'
    container_name: 'db'
    environment:
      - 'POSTGRES_DB=notes_db'
      - 'POSTGRES_PASSWORD=Password1!'
      - 'POSTGRES_USER=notes'
    ports:
      - '5432'
    networks:
      - app-network
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  secure-notes-app:
    container_name: 'secure-notes-app'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    ports:
      - '443:3443'
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
