services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=notes_db'
      - 'POSTGRES_PASSWORD=Password1!'
      - 'POSTGRES_USER=notes'
    ports:
      - '5432'
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
